create table ads(
 id integer generated by default as identity primary key,
 users_id integer references users(id),
 image_id integer references image(id),
 price integer,
 title varchar,
 description varchar
 );